version: '3.8'

services:
  # Backend server (production)
  server:
    build:
      context: ./server
      target: production
    container_name: interiit-server-prod
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_SECRET=${ADMIN_SECRET}
    networks:
      - app-network
    restart: always
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:4000/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend client (production with nginx)
  client:
    build:
      context: ./client
      target: production
      args:
        - VITE_API_BASE=${VITE_API_BASE:-http://localhost:4000/api}
    container_name: interiit-client-prod
    ports:
      - "80:80"
    networks:
      - app-network
    restart: always
    depends_on:
      - server
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  app-network:
    driver: bridge
